### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by pgoodling-usgs** [USGS-R/intersectr#29]
When I try to install using `devtools::install_github("USGS-R/intersectr")` while running R 4.1.0 on Windows 10 x64, I receive this error:

```Error: package or namespace load failed for 'intersectr' in namespaceExport(ns, exports):  undefined exports: calculate_area_intersection_weights```

I tried updating all affected packages and still have the error. I can run the source code for `calculate_area_intersection_weights.R` just fine if I download the file separately. But otherwise I'm unable to trace the issue.

**Comment by dblodgett-usgs** [comment]
Sorry about that -- I'm parting this package out and will be moving the core functionality to `geoknife`. That work is ongoing. 

In the mean time, please use `v0.0.3` 

devtools::install_github("USGS-R/intersectr@v0.0.3")

I will also just bring the "main" branch back to that tag and put some stuff back that I removed. Sorry for the trouble.

**Comment by pgoodling-usgs** [comment]
Thanks!! Worked like a charm. No trouble.
